name: Format
on: [push, workflow_dispatch, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format Files
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - name: Prettier
        run: npx prettier --write Data.json
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          commit_message: 'style: format files'
